### ISSUE TITLE
A problem occurred during installation

### ISSUE THREAD

**Issue by HansOffice** [SkinsRestorer/SkinSystem#132]
Display after installing the configuration file,I want to know exactly where the configuration went wrong
Fatal error: Uncaught PDOException: SQLSTATE[HY000] [1130] Host '42.193.122.45' is not allowed to connect to this MySQL server in C:\wwwroot\www.cyumc.ltd\skin\resources\server\libraries.php:19 Stack trace: #0 C:\wwwroot\www.cyumc.ltd\skin\resources\server\libraries.php(19): PDO->__construct('mysql:host=www....', 'skin', 'hans1101') #1 C:\wwwroot\www.cyumc.ltd\skin\index.php(3): require_once('C:\\wwwroot\\www....') #2 {main} thrown in C:\wwwroot\www.cyumc.ltd\skin\resources\server\libraries.php on line 19

**Comment by xknat** [comment]
> Display after installing the configuration file,I want to know exactly where the configuration went wrong Fatal error: Uncaught PDOException: SQLSTATE[HY000] [1130] Host '42.193.122.45' is not allowed to connect to this MySQL server in C:\wwwroot\www.cyumc.ltd\skin\resources\server\libraries.php:19 Stack trace: #0 C:\wwwroot\www.cyumc.ltd\skin\resources\server\libraries.php(19): PDO->__construct('mysql:host=www....', 'skin', 'hans1101') #1 C:\wwwroot\www.cyumc.ltd\skin\index.php(3): require_once('C:\wwwroot\www....') #2 {main} thrown in C:\wwwroot\www.cyumc.ltd\skin\resources\server\libraries.php on line 19

Host '42.193.122.45' is not allowed to connect to this MySQL server

**Comment by HansOffice** [comment]
> > 安装配置文件后显示,我想知道具体哪里配置出错了致命错误: Uncaught PDOException: SQLSTATE[HY000] [1130] Host '42.193.122.45' is not allowed to connect to this MySQL server in C:\wwwroot \www.cyumc.ltd\skin\resources\server\libraries.php:19 堆栈跟踪：#0 C:\wwwroot\www.cyumc.ltd\skin\resources\server\libraries.php(19)：PDO-> __construct('mysql:host=www....', 'skin', 'hans1101') #1 C:\wwwroot\www.cyumc.ltd\skin\index.php(3): require_once('C:\ wwwroot\www....') #2 {main} 在第 19 行的 C:\wwwroot\www.cyumc.ltd\skin\resources\server\libraries.php 中抛出
> 
> 不允许主机 '42.193.122.45' 连接到此 MySQL 服务器

What should I do?

**Comment by xknat** [comment]
you should allow the mentioned ip to your MYSQL server (whitelist / allowlist)

**Comment by HansOffice** [comment]
> 你应该允许提到的IP到你的MYSQL服务器（白名单/白名单）

I don't quite understand. This IP is my MySQL server IP. Is it necessary for me to open something for this? The server does not report errors due to MySQL configuration files. In addition, can MySQL built on the local server solve this problem?
